### PR TITLE
Fixed some UI parts.

### PR DESCRIPTION
**Pull request by fauyds**
Fixed some UI parts for the OnePlus 7T Pro (hotdog)
-Paddings of the bottom shortcuts on the lockscreen.
-The bottom padding for the QQS.

### CODE REVIEW

**Comment by ShevT** [comment]
> -Paddings of the bottom shortcuts on the lockscreen.

Yes, it looks good.

> The bottom padding for the QQS

It's too big a deal. It looks bad. We leave it by default.

**Comment by fauyds** [comment]
This is 24dp.

Does it looks that bad?

**Comment by fauyds** [comment]
What about 20dp?

The same as notification padding.

**Comment by ShevT** [comment]
I left it like [this](https://github.com/crdroidandroid/android_device_oneplus_hotdog/commit/a311ed37d8908f5597cf757704a0038d92cd9990).

**Pull request closed without merging**
